### ISSUE TITLE
Fixing Talks floats

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#44]
When display the talks for a given day, they are messy. @goulvench I guess you will be quicker than me reguarding this point.

Thanks!

Related to #33

**Comment by goulvench** [comment]
I believe that these blocks should simply _not_ float, because presenting
chronological items side by side suggests that they happen simultaneously,
which is not the case here.

The easiest solution is therefore to just remove float declarations in the

## CSS.

Goulven Champenois

On Fri, Mar 2, 2012 at 12:22 PM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
Ok so let's show them the same way we display the global schedule (so removing the floating).
